name: flutter_products_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_provider: ^2.1.0
  flutter_riverpod: ^2.3.6
  flutter_speed_dial: ^7.0.0
  go_router: ^10.0.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  riverpod: ^2.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
